### ISSUE TITLE
Forward endcap incorrect z-position

### ISSUE THREAD

**Issue by rymilton** [eic/epic#165]
**Is your feature request related to a problem? Please describe.**
The forward endcap is at the incorrect z-position in simulation compared to the [latest parameters table](https://eic.jlab.org/Geometry/Detector/Detector-20220929172703.html). ECal in simulation is at 333 cm, compared to 329.6 cm in the table. HCal in simulation is at 363 cm, compared to 359.6 cm in the table.

**Describe the solution you'd like**
Currently, the simulation z-positions depend on other the positions of other detector systems. It would be easiest to hard-code the z-positions for the forward endcap calorimeters.

**Describe alternatives you've considered**
Track down the discrepancies in the other systems and adjust those z-positions.

**Comment by rymilton** [comment]
Authors of the forward endcap code have opted to hard-code the z-positions. 

Note this means that there's an incorrect z-position somewhere for another system that should be tracked down and adjusted. Please make sure the z of your detector system is correct.

**Comment by wdconinc** [comment]
Let's go with the alternative solution here.

**Comment by rymilton** [comment]
So we should stick with the z positions for all systems being dependent on each other? Either way, we should find the discrepancy of course.

**Comment by wdconinc** [comment]
Current detector parameter table in simulation: https://github.com/eic/epic/suites/8636294046/artifacts/388022152

Current detector parameter table from project: https://eic.jlab.org/Geometry/Detector/Detector-20220929172703.html

Here are some changes I can identify, if we take the detector parameter table at face value:
- ForwardServiceGap_length should be 10 cm (even though parameter table has 9 cm, that's due to improper rounding; 329.6 cm doesn't correspond to 329 cm)
- ForwardPIDRegion_length should be 135 cm, not 142 cm (dRICH @c-dilks + TOF @nschmidtALICE)
- CentralTrackingRegionP_zmax should be 180 cm, not 173 cm (@sly2j)
- CentralTrackingRegionN_zmax should be 130 cm, not 147.47 cm (@sly2j), or even 118.6 cm in the pfRICH config.

**Comment by wdconinc** [comment]
@c-dilks Definitely! Or equivalently the DetectorParameterTable.csv spreadsheet which is supposed to mirror the one from the project.
